modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="noctisheroes"
version="1.0.0"
displayName="Noctis Heroes"
description="Mobs e poderes com Palladium"

[[dependencies.noctisheroes]]
modId="forge"
mandatory=true
versionRange="[47,)"
side="BOTH"

[[dependencies.noctisheroes]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
side="BOTH"

[[dependencies.noctisheroes]]
modId = "palladium"
mandatory = true
versionRange = "[1.20.1-4.5.4,)"
ordering = "AFTER"
side = "BOTH"